var htmlWebpackPlugin = require('html-webpack-plugin');

var path = require('path');

module.exports = {
	entry:{
		mySelect:"./public/select/mySelect.js"
	},
	output:{
		filename:'js/[name].bundle.js',
		path:path.resolve(__dirname,'dist')
	},
	module:{
		rules:[
			{
				test:/\.css$/,
				use:[
					{
						loader:'style-loader'
					},
					{
						loader:'css-loader',
						options:{
							//modules:true,
							importLoaders:1
						}
					},
					{
						loader:'postcss-loader',
						options:{
							plugins:function(){
								return [
									//require('precss'),
									require('autoprefixer')
								];
							}
						}
					}
				]
			},
			{
				test:/\.scss$/,
				use:[
					{
						loader:'style-loader'
					},
					{
						loader:'css-loader',
						options:{
							modules:true
						}
					},
					{
						loader:'postcss-loader',
						options:{
							plugins:function(){
								return [
									require('precss'),
									require('autoprefixer')
								];
							}
						}
					},
					{
						loader:'sass-loader'
					}
				]
			},
			{
				test:/\.html$/,
				use:[
					{
						loader:'html-loader'
					}
				]
			},
			{
				test:/\.(png|jpg|jpeg|gif|bmp)$/i,
				use:[
					{
						loader:'file-loader',
						options:{
							//limit:8192,
							name:'images/[name].[hash:7].[ext]'
						}
					},
					{
						loader:"image-webpack-loader",
						options:{
							query:{
								mozjpeg:{
									progressive:true
								},
								gifsicle:{
									interlaced:false
								},
								optipng:{
									optimizationLevel:7
								},
								pngquant:{
									quality:'65-90',
									speed:4
								}
							}
						}

					}
				]
			},
			{
				test:/\.(svg|woff|woff2|ttf|eot|)$/i,
				use:[
					{
						loader:'url-loader'
					}
				]
			},
			{
				test:/\.tpl$/,
				use:[
					{
						loader:'ejs-loader'
					}				
				]
			},
			{
				test:require.resolve('jquery'),
				use:[
					{
						loader:'expose-loader',
						options:'jQuery'
					},
					{
						loader:'expose-loader',
						options:'$'
					}
				]
			},
			{
				test:/\.js$/,
				exclude:path.resolve(__dirname,'node_modules'),
				include:path.resolve(__dirname,'public/javascripts'),
				use:[
					{
						loader:'babel-loader',
						options:{

						}
					}
				]
			}
		]
	},
	plugins:[
		new htmlWebpackPlugin({
			template:"public/index.html",
			filename:"index.html",
			inject:"head",
			chunks:['mySelect']
		}),
	]
}